In [2]:
from zeni.basic_types import Addressable
Addressable(["a",1])

AttributeError: 'int' object has no attribute 'replace'

In [2]:

import pandas as pd

monzo = pd.read_csv("data/samples/monzo.csv")

In [6]:
set(monzo["Category"].values)

{'Bills',
 'Eating out',
 'Entertainment',
 'General',
 'Groceries',
 'Income',
 'Personal care',
 'Savings',
 'Shopping',
 'Transfers'}

In [7]:
monzo[monzo["Type"] == 'Monzo-to-Monzo']

,Transaction ID,Date,Time,Type,Name,Emoji,Category,Amount,Currency,Local amount,Local currency,Notes and #tags,Address,Receipt,Description,Category split,Money Out,Money In
20,tx_0000AuBvAVTqvNsXRQAkjp,17/05/2025,17:02:50,Monzo-to-Monzo,Eleanor Hutchison,NaN,General,5.0,GBP,5.0,GBP,NaN,NaN,NaN,NaN,NaN,NaN,5.0
23,tx_0000AuJmn6QWf7EBQNXCj3,21/05/2025,12:06:40,Monzo-to-Monzo,Caitlin Fearon,NaN,General,35.0,GBP,35.0,GBP,NaN,NaN,NaN,NaN,NaN,NaN,35.0

In [ ]:
monzo[monzo["Category"] == "Bills"]

,Transaction ID,Date,Time,Type,Name,Emoji,Category,Amount,Currency,Local amount,Local currency,Notes and #tags,Address,Receipt,Description,Category split,Money Out,Money In
1,tx_0000AtdScAqXjPDtOMWUOP,01/05/2025,02:01:58,Direct Debit,Etika,NaN,Bills,-9.50,GBP,-9.50,GBP,238000681980,NaN,NaN,238000681980,NaN,-9.50,NaN
14,tx_0000AtqekR6kscrWE5dnxS,07/05/2025,10:49:55,Card payment,Spotify,🎵,Bills,-11.99,GBP,-11.99,GBP,NaN,1-11 John Adam Street,NaN,Spotify London GBR,NaN,-11.99,NaN
31,tx_0000Auhv6WnSJ3SxqiXAOH,02/06/2025,03:32:53,Direct Debit,Etika,NaN,Bills,-9.50,GBP,-9.50,GBP,238000681980,NaN,NaN,238000681980,NaN,-9.50,NaN
36,tx_0000AusugAZqQtTSf8QgcN,07/06/2025,10:49:57,Card payment,Spotify,🎵,Bills,-11.99,GBP,-11.99,GBP,NaN,1-11 John Adam Street,NaN,Spotify London GBR,NaN,-11.99,NaN
52,tx_0000AvfzJioYzcrGYFXKV8,01/07/2025,03:02:46,Direct Debit,Etika,NaN,Bills,-9.50,GBP,-9.50,GBP,238000681980,NaN,NaN,238000681980,NaN,-9.50,NaN
55,tx_0000Avt65qeYHHDTIZIvjN,07/07/2025,10:49:57,Card payment,Spotify,🎵,Bills,-11.99,GBP,-11.99,GBP,NaN,1-11 John Adam Street,NaN,Spotify London GBR,NaN,-11.99,NaN

In [ ]:
parsed = parse_monzo(monzo)

In [ ]:
parsed

,StandardColumns.DATE,StandardColumns.TIME,StandardColumns.TYPE,StandardColumns.CATEGORY,StandardColumns.NAME,StandardColumns.AMOUNT,StandardColumns.CURRENCY,amount,category,currency,date,time,name,type
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.05,Transfers,GBP,01/05/2025,02:01:58,Round Ups Pot,Pot transfer
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9.50,Bills,GBP,01/05/2025,02:01:58,Etika,Direct Debit
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.06,General,GBP,01/05/2025,03:03:00,nan,overdraft
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.15,Entertainment,GBP,01/05/2025,05:01:26,Current Affairs,Card payment
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.85,Savings,GBP,01/05/2025,05:01:27,Round Ups Pot,Pot transfer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.00,Transfers,GBP,26/07/2025,08:08:24,BRENDAN REID,Faster payment
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-20.00,Shopping,GBP,27/07/2025,00:15:02,Harry's,Card payment
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.00,Transfers,GBP,27/07/2025,06:16:24,BRENDAN REID,Faster payment
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326.00,Transfers,GBP,31/07/2025,05:27:44,BRENDAN REID,Faster payment
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-219.09,Transfers,GBP,31/07/2025,05:27:54,nan,Flex

In [ ]:
from zeni.parse.parser import PERFERRED_ORDERING

PERFERRED_ORDERING

TypeError: getattr() takes no keyword arguments

In [ ]:
from zeni.types import StandardColumns

("value",) * len(StandardColumns)

('value', 'value', 'value', 'value', 'value', 'value', 'value')